# Generated by Django 5.2.11 on 2026-03-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_address_address_type_alter_address_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(default='Home', max_length=50),
        ),
    ]
