# Generated by Django 5.2.11 on 2026-03-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
