# Generated by Django 5.2.11 on 2026-04-01 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_vendor_account_holder_name_vendor_account_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
    ]
