# Generated by Django 5.2.11 on 2026-02-23 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_partner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
