# Generated by Django 5.2.11 on 2026-02-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_user_is_partner_remove_user_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='default_quantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
