# Generated by Django 5.2.11 on 2026-02-23 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_image_url_category_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
