# Generated by Django 5.2.11 on 2026-02-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_name_category_name_en_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
