# Generated by Django 5.2.11 on 2026-02-26 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=3)),
                ('opening_time', models.CharField(default='6:00 AM', max_length=50)),
                ('closing_time', models.CharField(default='9:00 PM', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.CharField(max_length=50)),
                ('protein', models.CharField(max_length=50)),
                ('fat', models.CharField(max_length=50)),
                ('carbs', models.CharField(max_length=50)),
                ('per_unit', models.CharField(default='100ml', max_length=50)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shop_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.shopdetail'),
        ),
    ]
