# Generated by Django 5.2.11 on 2026-03-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_shopdetail_nutrition_product_shop_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopdetail',
            old_name='address',
            new_name='address_en',
        ),
        migrations.RenameField(
            model_name='shopdetail',
            old_name='shop_name',
            new_name='shop_name_en',
        ),
        migrations.AddField(
            model_name='shopdetail',
            name='address_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopdetail',
            name='address_mr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopdetail',
            name='address_ur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopdetail',
            name='shop_name_hi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopdetail',
            name='shop_name_mr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopdetail',
            name='shop_name_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
