# Generated by Django 5.2.11 on 2026-03-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_address_shopdetail_address_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_mr',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ur',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_mr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_ur',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_mr',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name_ur',
        ),
        migrations.RemoveField(
            model_name='shopdetail',
            name='address_mr',
        ),
        migrations.RemoveField(
            model_name='shopdetail',
            name='address_ur',
        ),
        migrations.RemoveField(
            model_name='shopdetail',
            name='shop_name_mr',
        ),
        migrations.RemoveField(
            model_name='shopdetail',
            name='shop_name_ur',
        ),
    ]
