# Generated by Django 5.2.11 on 2026-03-26 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_category_name_mr_remove_category_name_ur_and_more'),
        ('users', '0013_alter_customer_email_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetail',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_details', to='users.vendor', to_field='vendor_id'),
        ),
    ]
