# Generated by Django 5.2.11 on 2026-03-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_shopdetail_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopdetail',
            name='vendor',
        ),
        migrations.AddField(
            model_name='shopdetail',
            name='shop_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopdetail',
            name='shop_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shopdetail',
            name='vendor_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
