# Generated by Django 5.2.11 on 2026-03-26 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_shopdetail_vendor_shopdetail_shop_address_and_more'),
        ('users', '0013_alter_customer_email_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopdetail',
            name='shop_address',
        ),
        migrations.RemoveField(
            model_name='shopdetail',
            name='shop_name',
        ),
        migrations.RemoveField(
            model_name='shopdetail',
            name='vendor_id',
        ),
        migrations.AddField(
            model_name='shopdetail',
            name='vendor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_detail', to='users.vendor', to_field='vendor_id'),
        ),
    ]
