# Generated by Django 5.2.11 on 2026-03-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_created_at_product_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
