# Generated by Django 5.2.11 on 2026-02-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportmessage',
            name='email',
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
