# Generated by Django 5.2.11 on 2026-03-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_remove_supportmessage_email_supportmessage_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer_mr',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_ur',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_mr',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_ur',
        ),
    ]
