# Generated by Django 5.2.11 on 2026-03-01 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0007_shopdetail_nutrition_product_shop_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.URLField()),
                ('link_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_hi', models.CharField(blank=True, max_length=255, null=True)),
                ('title_mr', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ur', models.CharField(blank=True, max_length=255, null=True)),
                ('description_en', models.TextField()),
                ('description_hi', models.TextField(blank=True, null=True)),
                ('description_mr', models.TextField(blank=True, null=True)),
                ('description_ur', models.TextField(blank=True, null=True)),
                ('discount_code', models.CharField(max_length=50, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Percentage discount', max_digits=5)),
                ('image', models.URLField(blank=True, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Coupon', 'Coupon'), ('Bank', 'Bank'), ('Exclusive', 'Exclusive')], default='Coupon', max_length=20)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('title_en', models.CharField(max_length=255)),
                ('title_hi', models.CharField(blank=True, max_length=255, null=True)),
                ('description_en', models.TextField()),
                ('description_hi', models.TextField(blank=True, null=True)),
                ('expiry_text', models.CharField(max_length=100)),
                ('color', models.CharField(default='#3b82f6', max_length=50)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_type', models.CharField(default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('applicable_categories', models.JSONField(blank=True, default=list)),
                ('image', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='product.product')),
            ],
        ),
    ]
