# Generated by Django 5.2.11 on 2026-03-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='subtitle',
            new_name='subtitle_en',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='banner',
            name='product_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle_hi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle_mr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_hi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_mr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
