# Generated by Django 5.2.11 on 2026-03-10 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_address_shopdetail_address_en_and_more'),
        ('promotion', '0002_rename_subtitle_banner_subtitle_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='product_ids',
        ),
        migrations.AddField(
            model_name='banner',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='banners', to='product.product'),
        ),
    ]
