# Generated by Django 5.2.11 on 2026-03-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_remove_banner_product_ids_banner_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='subtitle_mr',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='subtitle_ur',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title_mr',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='title_ur',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='description_mr',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='description_ur',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='title_mr',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='title_ur',
        ),
    ]
