# Generated by Django 5.2.11 on 2026-02-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscription_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='quantity',
            new_name='quantity_litres',
        ),
        migrations.AddField(
            model_name='subscription',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
