# Generated by Django 5.2.11 on 2026-02-27 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_shopdetail_nutrition_product_shop_detail'),
        ('subscriptions', '0003_rename_quantity_subscription_quantity_litres_and_more'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='slot',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('both', 'Both')], default='morning', max_length=20),
        ),
        migrations.CreateModel(
            name='MonthlySubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=20)),
                ('slot', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('both', 'Both')], default='morning', max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('quantity_litres', models.PositiveIntegerField(default=1)),
                ('plan_subscribed_date', models.DateField(auto_now_add=True)),
                ('subscription_end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_subscriptions', to='users.address')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_subscribers', to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YearlySubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=20)),
                ('slot', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('both', 'Both')], default='morning', max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('quantity_litres', models.PositiveIntegerField(default=1)),
                ('plan_subscribed_date', models.DateField(auto_now_add=True)),
                ('subscription_end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yearly_subscriptions', to='users.address')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_subscribers', to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SubscriptionPause',
        ),
    ]
