# Generated by Django 5.2.11 on 2026-02-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_remove_subscription_user_subscription_desc_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysubscriber',
            name='desc_en',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='desc_hi',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='desc_mr',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='desc_ur',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='frequency_en',
            field=models.CharField(default='Daily', max_length=255),
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='frequency_hi',
            field=models.CharField(default='दैनिक', max_length=255),
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='frequency_mr',
            field=models.CharField(default='दैनिक', max_length=255),
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='frequency_ur',
            field=models.CharField(default='روزانہ', max_length=255),
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='plan_name_en',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='plan_name_hi',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='plan_name_mr',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='plan_name_ur',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='slot_en',
            field=models.CharField(default='Morning', max_length=255),
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='slot_hi',
            field=models.CharField(default='सुबह', max_length=255),
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='slot_mr',
            field=models.CharField(default='सकाळ', max_length=255),
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='slot_ur',
            field=models.CharField(default='صبح', max_length=255),
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='status_en',
            field=models.CharField(default='Active', max_length=255),
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='status_hi',
            field=models.CharField(default='सक्रिय', max_length=255),
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='status_mr',
            field=models.CharField(default='सक्रिय', max_length=255),
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='status_ur',
            field=models.CharField(default='فعال', max_length=255),
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='desc_en',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='desc_hi',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='desc_mr',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='desc_ur',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='frequency_en',
            field=models.CharField(default='Daily', max_length=255),
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='frequency_hi',
            field=models.CharField(default='दैनिक', max_length=255),
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='frequency_mr',
            field=models.CharField(default='दैनिक', max_length=255),
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='frequency_ur',
            field=models.CharField(default='روزانہ', max_length=255),
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='plan_name_en',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='plan_name_hi',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='plan_name_mr',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='plan_name_ur',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='slot_en',
            field=models.CharField(default='Morning', max_length=255),
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='slot_hi',
            field=models.CharField(default='सुबह', max_length=255),
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='slot_mr',
            field=models.CharField(default='सकाळ', max_length=255),
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='slot_ur',
            field=models.CharField(default='صبح', max_length=255),
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='status_en',
            field=models.CharField(default='Active', max_length=255),
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='status_hi',
            field=models.CharField(default='सक्रिय', max_length=255),
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='status_mr',
            field=models.CharField(default='सक्रिय', max_length=255),
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='status_ur',
            field=models.CharField(default='فعال', max_length=255),
        ),
    ]
