# Generated by Django 5.2.11 on 2026-02-27 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_monthlysubscriber_desc_en_monthlysubscriber_desc_hi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='start_date',
        ),
    ]
