# Generated by Django 5.2.11 on 2026-02-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_remove_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
