# Generated by Django 5.2.11 on 2026-02-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_subscription_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='category',
            field=models.CharField(choices=[('Monthly Essentials', 'Monthly Essentials'), ('Monthly Organic', 'Monthly Organic'), ('Yearly Family Packs', 'Yearly Family Packs'), ('Yearly Organic', 'Yearly Organic')], default='Monthly Essentials', max_length=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_best_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='unit',
            field=models.CharField(default='Monthly', max_length=50),
        ),
    ]
