# Generated by Django 5.2.11 on 2026-03-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_remove_monthlysubscriber_desc_mr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysubscriber',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='is_paused_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='original_subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='is_paused_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='original_subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlysubscriber',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='yearlysubscriber',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='daily', max_length=20),
        ),
    ]
