# Generated by Django 5.2.11 on 2026-03-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_monthlysubscriber_is_paused_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysubscriber',
            name='daily_delivery_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('on_the_way', 'On the Way'), ('delivered', 'Delivered')], default='confirmed', max_length=20),
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='daily_delivery_status_en',
            field=models.CharField(default='Confirmed', max_length=20),
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='daily_delivery_status_hi',
            field=models.CharField(default='पुष्टी केली', max_length=20),
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='daily_delivery_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('on_the_way', 'On the Way'), ('delivered', 'Delivered')], default='confirmed', max_length=20),
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='daily_delivery_status_en',
            field=models.CharField(default='Confirmed', max_length=20),
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='daily_delivery_status_hi',
            field=models.CharField(default='पुष्टी केली', max_length=20),
        ),
    ]
