# Generated by Django 5.2.11 on 2026-03-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_monthlysubscriber_daily_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysubscriber',
            name='plan_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='plan_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
