# Generated by Django 5.2.11 on 2026-04-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0014_monthlysubscriber_plan_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysubscriber',
            name='status_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='status_delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlysubscriber',
            name='status_shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='status_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='status_delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yearlysubscriber',
            name='status_shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
