# Generated by Django 5.2.11 on 2026-04-03 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_monthlysubscriber_status_confirmed_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlysubscriber',
            old_name='status_shipped_at',
            new_name='status_ontheway_at',
        ),
        migrations.RenameField(
            model_name='yearlysubscriber',
            old_name='status_shipped_at',
            new_name='status_ontheway_at',
        ),
    ]
