# Generated by Django 5.2.11 on 2026-03-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='vendor_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
