# Generated by Django 5.2.11 on 2026-03-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='vendor_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
