# Generated by Django 5.2.11 on 2026-03-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment'), ('upi', 'UPI'), ('card', 'Credit/Debit Card')], default='cod', max_length=20),
        ),
    ]
