# Generated by Django 5.2.11 on 2026-04-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status_delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status_ontheway_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
