# Generated by Django 5.2.11 on 2026-04-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_status_cancelled_at_order_status_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_subscription_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='subscriber_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20, null=True),
        ),
    ]
